########################
### MACRO: Cobalt 60 ###
########################

# Distance units: [mm]  

/source/isIon 1
/source/Z 27
/source/A 60

# Cube dimensions
/cube/Cube_Width 10
/cube/Cube_Length 10
/cube/Cube_Height 10

# Cube-centre position
/cube/xCube 40
/cube/yCube 0
/cube/zCube 5

# Lithium relative abundances
/cube/Li7_percent 93
/cube/Li6_percent 7

/run/initialize
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+3 year